apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-nufs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-nufs
    app.kubernetes.io/part-of: test-annotations-app-pcxs
  name: test-annotations-nufsfnyq
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-annotations-nufs
    weight: 100
status: {}
